global:
  scrape_interval: 15s
  external_labels:
    datacenter: "laptop"

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          team: "monitoring"
